language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no test"

# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
script:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-api-frontend ./udagram-api-frontend
- docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
- docker tag udagram-api-feed harubebe/udagram-api-feed:v1
- docker tag udagram-api-user harubebe/udagram-api-user:v1
- docker tag udagram-api-frontend harubebe/udagram-api-frontend:v1
- docker tag udagram-api-reverseproxy harubebe/udagram-api-reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push harubebe/udagram-api-feed:v1
- docker push harubebe/udagram-api-user:v1
- docker push harubebe/udagram-api-frontend:v1
- docker push harubebe/udagram-api-reverseproxy:v1
